version: 2.1

jobs:
  build-server:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: sudo apt-get update && sudo apt-get install -y build-essential curl libsqlite3-dev
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: cd server && cargo build --release

workflows:
  build:
    jobs:
      - build-server