-- Your SQL goes here
CREATE TABLE users (
  id AUTO_INCREMENT INTEGER PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT 'f'
)