name: build

on:
  push:
    branches:
      - master
      - gh-actions

env:
  YARN_CACHE: 001

jobs:
  release:
    timeout-minutes: 10
    if: github.event_name == 'push'
    runs-on: macos-latest
    strategy:
      matrix:
        rust-target: [ 'x86_64-unknown-linux-gnu', 'i686-unknown-linux-gnu', 'aarch64-unknown-linux-gnu' ]
    name: Rust stable-${{ matrix.rust-target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Move server dir to root
        run: mv server/* .
      - name: Install podman
        run: apt-get -y update && apt-get -y install podman
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.5
#         with:
#           version: 14
#       - uses: actions/cache@v2
#         with:
#           path: '**/node_modules'
#           key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#       - name: Install Yarn
#         run: npm i -g yarn && yarn
#       - name: Build www
#         run: yarn build:www
      - name: rust-toolchain
        # You may pin to the exact commit or the version.
        # uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.rust-target }}
      - uses: Swatinem/rust-cache@v1
#       - name: Zip Release
#         uses: TheDoctor0/zip-release@0.4.2
#         with:
          # Filename for archive
#           filename: ${{ matrix.rust-target }}.zip
          # Base path for archive files
#           path: # optional, default is .
#           # Working directory before zipping
#           directory: # optional, default is .
#           # List of excluded files / directories
#           exclusions: # optional, default is 
#           # Tool to use for archiving
#           type: # optional, default is zip
