name: build

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  release:
    timeout-minutes: 10
    if: github.event_name == 'push'
    runs-on: ubuntu-18.04
    name: Release aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y docker
      - name: pull docker image
        run: docker pull adeyahya/rust-arm64
      - name: start docker
        run: docker run -i -d -v ${PWD}/server/:/app --name builder adeyahya/rust-arm64
      - name: build server
        run: docker exec -it builder /root/.cargo/bin/cargo build --release
