name: build

on:
  push:
    branches:
      - master
      - gh-actions

env:
  YARN_CACHE: 001

jobs:
  release:
    timeout-minutes: 10
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          version: 14
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn
        run: npm i -g yarn && yarn
      - name: Build www
        run: yarn build:www
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          overwrite: true
      - name: Build server
        run: cd server && cargo build --release
