name: build

on:
  push:
    branches:
      - master
      - gh-actions

env:
  YARN_CACHE: 001

jobs:
  release:
    timeout-minutes: 10
    if: github.event_name == 'push'
    runs-on: macos-latest
    strategy:
      matrix:
        rust-host: [ 'x86_64-unknown-linux-gnu', 'i686-unknown-linux-gnu', 'x86_64-apple-darwin' ]
    name: Rust stable-${{ matrix.rust-host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2.1.5
#         with:
#           version: 14
#       - uses: actions/cache@v2
#         with:
#           path: '**/node_modules'
#           key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
#       - name: Install Yarn
#         run: npm i -g yarn && yarn
#       - name: Build www
#         run: yarn build:www
      - uses: raftario/setup-rust-action@v1
        with:
          rust-channel: stable
          rust-host: ${{ matrix.rust-host }}
      - uses: Swatinem/rust-cache@v1
      - name: Build server
        run: cd server && cargo build --release
